# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.2.105'
  inputs:
    version: 2.2.105
    
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.9.4'
  inputs:
    versionSpec: 4.9.4

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    vstsFeed: '1aaa557e-474c-4e89-93ff-0776209b7d36'

#- script: dotnet restore -s https://pkgs.dev.azure.com/karannandwani/_packaging/GoodFeed/nuget/v3/index.json vstsFeed: 'af78cfbf-e237-4f70-8918-2b59d3607411'
#  displayName: 'dotnet restore'

- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
  displayName: 'dotnet publish'

- task: PublishBuildArtifacts@1
